import Head from "next/head"
import { ReactNode } from "react"

interface PropType {
    children : ReactNode;
}

export default function Layout({children} : PropType):JSX.Element{
    return(
        <>
        <Head>
          <title>Team Project</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            {children}
        </main>
      </>
    )
}